version: '3.8'

services:
  python_app:
    image: python:3.11-slim
    volumes:
      - .:/app
    environment:
      - DB_HOST=my-postgres
    network_mode: "host"

  postgres:
    external: true
    name: my-postgres